const courseCategories = [
    'Dance',
    'Music',
    'Chess',
    'Karate',
    'Art',
    'Cooking',
    'Yoga',
    'Programming',
    'Photography',
    'Languages',
    'Mathematics',
    'Science',
    'Writing',
    'Gardening',
    'Fitness',
    'Meditation',
    'History',
    'Literature',
    'Design',
    'Finance',
    'Business',
    'Technology',
    'Crafts',
    'Robotics',
    'Theater',
    'Sports',
    'Astrology',
    'Psychology',
    'Environmental Studies',
    'Philosophy',
    'DIY Projects',
    'Culinary Arts',
    'Fashion Design',
    'Graphic Design',
    'Marketing',
    'Animation',
    'Film Production',
    'Architecture',
  ];
  
  export default courseCategories;
  